# Generated by Django 2.0.4 on 2018-06-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blog_url',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='is_original',
            field=models.BooleanField(default=True),
        ),
    ]
