# Generated by Django 2.0.4 on 2018-07-24 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180604_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ('-pub_date',)},
        ),
    ]
