# Generated by Django 2.0.4 on 2018-07-05 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='collector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='word.Collector'),
        ),
    ]
