# Generated by Django 2.0.4 on 2018-07-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_auto_20180706_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='word',
            field=models.ManyToManyField(null=True, to='word.Word'),
        ),
    ]
