# Generated by Django 2.0.4 on 2018-07-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0004_auto_20180712_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='word',
            field=models.ManyToManyField(to='word.Word'),
        ),
    ]
