# Generated by Django 2.0.4 on 2018-07-13 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0005_auto_20180713_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collector',
            options={'ordering': ['-collect_time']},
        ),
    ]
