# Generated by Django 2.0.4 on 2018-07-17 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='image'),
            preserve_default=False,
        ),
    ]
