# Generated by Django 2.0.4 on 2018-07-23 08:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_is_bind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='mood_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=500),
        ),
    ]
