# Generated by Django 2.0.4 on 2018-06-27 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_auto_20180626_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['message_time']},
        ),
        migrations.AddField(
            model_name='message',
            name='root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='root_message', to='comment.Message'),
        ),
    ]
