# Generated by Django 2.0.4 on 2018-06-28 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_auto_20180627_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_message', to='comment.Message'),
        ),
    ]
