# Generated by Django 2.0.4 on 2018-07-05 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0009_remark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remark',
            options={'ordering': ['remark_time']},
        ),
    ]
