# Generated by Django 2.0.4 on 2018-07-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0010_auto_20180705_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-message_time']},
        ),
    ]
