# Generated by Django 2.0.4 on 2018-07-23 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0011_auto_20180723_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['message_time']},
        ),
    ]
